language: generic

services:
  - docker

before_install:
  - docker build -t dotoryeee/test-submit-server -f ./flask-submit-server/Dockerfile ./flask-submit-server

script:
  - docker run -e CI=true dotoryeee/test-submit-server python3 test.py

after_success:
  - docker build -t dotoryeee/flask-submit-server ./flask-submit-server
  - docker build -t dotoryeee/flask-result-server ./flask-result-server
  - docker build -t dotoryeee/nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push dotoryeee/flask-submit-server
  - docker push dotoryeee/flask-result-server
  - docker push dotoryeee/nginx

before_deploy:
  - zip -r myapp
  - mkdir deploy
  - mv myapp deploy

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: dotoryeee-s3
    region: ap-northeast-2
    #skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: dotoryeee-s3
    key: myapp.zip
    bundle_type: zip
    application: talentpool
    deployment_group: CICD-test
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main