FROM python:3
#.9.2-alpine

WORKDIR /usr/src/app
COPY ./ ./

RUN python3 -m pip install -U pip
#RUN apk add python3-dev build-base linux-headers pcre-dev
RUN pip3 install -r requirements.txt

CMD ["uwsgi", "uwsgi.ini"]